language: node_js
services:
  - docker
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '8'
after_success:
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
